name: Build

on:
  push:
    branches: [main]

permissions:
  contents: write

concurrency:
  group: "gist/resume.json"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: cd builder && npm clean-install
      - name: Compile to HTML and PDF
        run: node builder/builder.js
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist

  gist:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get Artifact
        uses: actions/download-artifact@v4
      - name: Update Gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: cadd0d13339210fde3095c195a47a602
          file_path: dist/resume.json

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get Artifact
        uses: actions/download-artifact@v4
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
